"""
Database layer for grade ingestion.

Follows the same conventions as `scraper/db.py` — `DATABASE_URL` and
`DATABASE_KEY` from the environment, `supabase-py` for transport — with one
deliberate difference: nothing here deletes.

The scraper clears a table before each run because Testudo data is a snapshot
that goes stale. Grade data is the opposite: each file is a permanent record of
one term, and terms accumulate. So loading is an upsert keyed on
(term, course_code, sec_code), which makes re-running any file harmless and
makes adding a single new term a matter of pointing the loader at one file.

The one destructive operation, `delete_term`, has to be asked for by name
(`--replace-term`) and exists for the case where a corrected file has *fewer*
rows than the one it supersedes, which an upsert alone would not clean up.
"""

import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from supabase import Client

# PostgREST will accept far more, but batching keeps a failed request small
# enough to identify and re-send.
CHUNK_SIZE = 1000

# Columns written to `grades`; anything else in a parsed record is ignored.
# `graded` and `gpa` are generated by the database and must not be sent.
GRADE_COLUMNS = (
    "term", "course_code", "sec_code",
    "instructor", "instructor_name", "instructor_source", "total",
    "a_plus", "a", "a_minus",
    "b_plus", "b", "b_minus",
    "c_plus", "c", "c_minus",
    "d_plus", "d", "d_minus",
    "f", "w", "other",
)


def get_supabase_client() -> "Client":
    # Imported here rather than at module scope so that `verify` and
    # `--print-output` run on a machine with neither the driver nor credentials.
    from supabase import create_client

    url = os.getenv("DATABASE_URL")
    if not url:
        raise EnvironmentError("DATABASE_URL not set in environment")
    key = os.getenv("DATABASE_KEY")
    if not key:
        raise EnvironmentError("DATABASE_KEY not set in environment")
    return create_client(url, key)


def _rows_for_upload(records: list[dict]) -> list[dict]:
    return [{column: record.get(column) for column in GRADE_COLUMNS} for record in records]


def chunked(items: list, size: int = CHUNK_SIZE):
    for start in range(0, len(items), size):
        yield items[start:start + size]


def upsert_grades(client: "Client", records: list[dict]) -> int:
    """
    Write grade records, replacing any row with the same
    (term, course_code, sec_code). Returns the number of rows sent.
    """
    rows = _rows_for_upload(records)
    for chunk in chunked(rows):
        client.table("grades").upsert(
            chunk, on_conflict="term,course_code,sec_code"
        ).execute()
    return len(rows)


def delete_term(client: "Client", term: int) -> None:
    """
    Remove every row for one term.

    Only needed when a replacement file has fewer rows than its predecessor, so
    that rows dropped by the registrar do not linger. `upsert_grades` handles
    every other case.
    """
    client.table("grades").delete().eq("term", term).execute()


def already_ingested(client: "Client", term: int, digest: str) -> bool:
    """True if this exact file has already been loaded for this term."""
    response = (
        client.table("grade_ingests")
        .select("id")
        .eq("term", term)
        .eq("file_sha256", digest)
        .limit(1)
        .execute()
    )
    return bool(response.data)


def record_ingest(client: "Client", report, digest: str) -> None:
    """Log one completed ingest for provenance."""
    client.table("grade_ingests").upsert(
        {
            "term": report.term,
            "source_file": report.source,
            "file_sha256": digest,
            "row_count": report.rows,
            "unaccounted_rows": report.unaccounted_rows,
            "unaccounted_students": report.unaccounted_students,
            # Truncated: a pathological file should not push a multi-megabyte
            # array into the log.
            "warnings": report.warnings[:50] or None,
        },
        on_conflict="term,file_sha256",
    ).execute()


def loaded_terms(client: "Client") -> list[dict]:
    """Every term currently in the database, with its section and row counts."""
    response = (
        client.table("grade_terms").select("*").order("term", desc=True).execute()
    )
    return response.data or []
