-- Instructor identity: a real primary key, every observed spelling as an
-- alias pointing at it, and a queue for the ones a machine should not guess.
--
-- Today `instructors` is keyed on PlanetTerp's slug and matched by exact name
-- string. The same person appears as "Walsh, Shane Bolles" in the registrar
-- exports, "Shane Bolles Walsh" after natural_name(), and "Shane Walsh" in
-- Testudo and PlanetTerp. Any join on the name string silently returns zero
-- rows for a large fraction of professors, and every failure looks like an
-- empty section rather than an error.

/* ========================== instructors rework ========================== */

alter table instructors
    -- Jupiterp-owned identity. `name` becomes display-only.
    add column if not exists id bigint generated by default as identity,
    add column if not exists name_norm text
        generated always as (normalize_name(name)) stored,

    -- PlanetTerp baseline, frozen at the one-time snapshot. Never written
    -- again: PlanetTerp is no longer being updated, so these are a historical
    -- record, not a feed.
    add column if not exists pt_slug           text,
    add column if not exists pt_average_rating numeric(3,2),
    add column if not exists pt_review_count   int,
    add column if not exists pt_snapshot_at    timestamptz,

    -- Jupiterp's own ratings, recomputed by a scheduled job rather than a
    -- trigger: the recency decay makes them time-dependent, so they change
    -- even on days when no review does.
    add column if not exists jupiterp_rating       numeric(3,2),
    add column if not exists jupiterp_review_count int not null default 0,
    add column if not exists combined_rating       numeric(3,2),

    -- Provenance and lifecycle.
    add column if not exists first_seen_term int,
    add column if not exists last_seen_term  int,
    add column if not exists is_active       boolean not null default false,
    add column if not exists created_at      timestamptz not null default now(),
    add column if not exists updated_at      timestamptz not null default now();

-- `id` has to be unique before anything can reference it. Added as a plain
-- unique index rather than a primary key because `slug` is the existing
-- primary key and moving it is a separate, riskier change with no benefit.
create unique index if not exists instructors_id_key on instructors (id);

create unique index if not exists instructors_slug_key on instructors (slug);
create index if not exists instructors_name_norm_idx on instructors (name_norm);

-- Backs both the resolver's fuzzy step and the API's `nameSearch` substring
-- filter. Without it, `name_norm ilike '%...%'` is a sequential scan over
-- every instructor on every keystroke of the professor directory search.
create index if not exists instructors_name_trgm_idx
    on instructors using gin (name_norm gin_trgm_ops);

-- `slug` changes meaning here: it was PlanetTerp's slug and becomes Jupiterp's
-- own. The old value moves to `pt_slug` so a redirect table can be built later
-- if inbound PlanetTerp links turn out to matter. This copy is a no-op on a
-- fresh database and runs once on the existing one.
update instructors set pt_slug = slug where pt_slug is null;

comment on column instructors.slug is
    'Jupiterp-owned URL slug, generated by next_instructor_slug(). Permanent '
    'once a professor page is published.';
comment on column instructors.pt_slug is
    'PlanetTerp''s slug, retained only for the one-time rating join and any '
    'future redirect table. Not used for routing.';
comment on column instructors.name is
    'Display name. Never join on this - use id, or resolve through '
    'instructor_aliases.';


/* ============================== aliases ================================= */

-- Every spelling of a name ever observed, from any source, pointing at the one
-- instructor it means.
--
-- Append-only. Deleting a row here does not just lose an alias, it orphans
-- every grade row that was matched through it, and the resolver will then
-- re-queue that name for a human who has no way to know it was decided before.
create table if not exists instructor_aliases (
    alias_norm    text primary key,
    -- As observed, for the audit trail: which exact string produced this link.
    alias_raw     text not null,
    instructor_id bigint not null references instructors (id) on delete cascade,
    source        text not null
        check (source in ('testudo', 'planetterp', 'registrar', 'manual')),
    -- < 1.0 means the link was inferred rather than seen. See the resolver in
    -- instructor_registry.py for what each level means.
    confidence    real not null default 1.0
        check (confidence > 0 and confidence <= 1.0),
    created_at    timestamptz not null default now()
);

create index if not exists instructor_aliases_instructor_idx
    on instructor_aliases (instructor_id);

-- The resolver's fuzzy step compares against alias spellings too, not just
-- `instructors.name`, so this needs the same trigram index.
create index if not exists instructor_aliases_trgm_idx
    on instructor_aliases using gin (alias_norm gin_trgm_ops);

comment on table instructor_aliases is
    'Append-only. Every observed spelling -> one instructor. Deleting a row '
    'orphans the grade rows matched through it.';


/* ============================ match queue =============================== */

-- Names the resolver refused to guess at. Expect low thousands on the first
-- full backfill across sixteen years of grade data.
--
-- The triage UI for this needs to exist BEFORE the backfill runs, not after:
-- the size of this queue is the single biggest unknown in the migration, and
-- discovering it is 10,000 rows with no way to work through them is how the
-- whole project stalls.
create table if not exists instructor_match_queue (
    id          bigserial primary key,
    observed    text not null,
    observed_norm text generated always as (normalize_name(observed)) stored,
    source      text not null
        check (source in ('testudo', 'planetterp', 'registrar', 'manual')),
    -- {course_code, term, sec_code} — enough to look the section up and decide
    -- who actually taught it.
    context     jsonb,
    -- Instructor ids that nearly matched, so triage is a choice rather than a
    -- search.
    candidates  bigint[],
    resolved_to bigint references instructors (id),
    resolved_at timestamptz,
    resolved_by text,
    created_at  timestamptz not null default now()
);

-- One open queue entry per distinct observed spelling per source. Without
-- this, a name that appears in 400 sections queues 400 identical decisions.
create unique index if not exists instructor_match_queue_open_idx
    on instructor_match_queue (observed_norm, source)
    where resolved_at is null;

create index if not exists instructor_match_queue_pending_idx
    on instructor_match_queue (created_at)
    where resolved_at is null;


/* ========================= slug generation ============================== */

-- Allocate a slug for a new instructor, suffixing on collision:
-- 'david-levin', then 'david-levin-2', 'david-levin-3'.
--
-- Two distinct professors genuinely do share a name, and the second one to be
-- discovered still needs a URL. The suffix is allocated by counting existing
-- matches rather than by scanning upward so that a deleted middle entry does
-- not cause a reused slug.
create or replace function next_instructor_slug(raw_name text)
returns text
language plpgsql
as $$
declare
    base      text := slugify(raw_name);
    candidate text;
    n         int  := 1;
begin
    if base is null or base = '' then
        raise exception 'cannot slugify name %', raw_name;
    end if;

    candidate := base;
    loop
        exit when not exists (select 1 from instructors where slug = candidate);
        n := n + 1;
        candidate := base || '-' || n;
    end loop;

    return candidate;
end;
$$;


/* =========================== updated_at ================================= */

create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists instructors_touch_updated_at on instructors;
create trigger instructors_touch_updated_at
    before update on instructors
    for each row execute function touch_updated_at();
