"""
Tests for the Management API clone script.

Nothing here talks to Supabase. The Project class is replaced with one that
records the SQL it would have sent, so two things can be checked without a
database:

  * every statement the script generates parses against PostgreSQL's real
    grammar, via libpg_query;
  * the pure functions -- column DDL, quoting, policy reconstruction --
    produce what they claim to.

That covers the failure this script is most likely to have, which is emitting
SQL that is subtly malformed for a shape of table nobody tested against.

    python3 tests/test_clone_via_api.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "db"))

import clone_via_api as clone  # noqa: E402

try:
    from pglast import parse_sql
    from pglast.parser import ParseError
    HAVE_PGLAST = True
except ImportError:  # pragma: no cover
    HAVE_PGLAST = False


class RecordingProject(clone.Project):
    """
    A Project that records SQL instead of sending it.

    `responder` receives the SQL and returns the rows to answer with, so a
    single stub can serve the several different shapes one code path asks for.
    """

    def __init__(self, rows=None, responder=None):
        super().__init__("testref", "token", "recording")
        self.statements: list[str] = []
        self._rows = rows or []
        self._responder = responder

    def query(self, sql: str, retries: int = 3):
        self.statements.append(sql)
        if self._responder is not None:
            return self._responder(sql)
        return self._rows


def check_parses(label: str, statements: list[str]) -> list[str]:
    if not HAVE_PGLAST:
        return []
    failures = []
    for sql in statements:
        try:
            parse_sql(sql)
        except ParseError as error:
            failures.append(f"{label}: {error}\n    {sql.strip()[:200]}")
    return failures


def test_introspection_sql_parses():
    """Every catalog query the script issues must be valid SQL."""
    project = RecordingProject()
    clone.fetch_enums(project)
    clone.fetch_tables(project)
    clone.fetch_columns(project, "grades")
    clone.fetch_constraints(project, "grades")
    clone.fetch_indexes(project, "grades")
    clone.fetch_views(project, materialized=False)
    clone.fetch_views(project, materialized=True)
    clone.fetch_functions(project)
    clone.fetch_rls(project)
    clone.fetch_grants(project)
    clone.unsupported_objects(project)
    clone.primary_key_columns(project, "grades")

    assert project.statements, "no SQL was generated"
    failures = check_parses("introspection", project.statements)
    assert not failures, "\n".join(failures)
    return len(project.statements)


def test_table_name_with_quote_is_escaped():
    """
    A table whose name contains an apostrophe must not break out of the
    literal it is embedded in. Unlikely in this schema, but the cost of
    getting it wrong is arbitrary SQL execution.
    """
    project = RecordingProject()
    clone.fetch_columns(project, "o'brien")
    sql = project.statements[0]
    assert "'public.o''brien'" in sql, sql
    assert not check_parses("escaping", [sql])


def test_column_ddl_shapes():
    cases = [
        # Plain column.
        ({"name": "course_code", "coltype": "text", "notnull": True,
          "coldefault": None, "identity": "", "generated": ""},
         '"course_code" text not null'),
        # Default.
        ({"name": "a", "coltype": "integer", "notnull": True,
          "coldefault": "0", "identity": "", "generated": ""},
         '"a" integer default 0 not null'),
        # Identity, which must not also emit its default.
        ({"name": "id", "coltype": "bigint", "notnull": True,
          "coldefault": None, "identity": "d", "generated": ""},
         '"id" bigint generated by default as identity not null'),
        ({"name": "id", "coltype": "bigint", "notnull": True,
          "coldefault": None, "identity": "a", "generated": ""},
         '"id" bigint generated always as identity not null'),
        # Stored generated column, as `grades.graded` and `grades.gpa` are.
        ({"name": "graded", "coltype": "integer", "notnull": False,
          "coldefault": "(a_plus + a)", "identity": "", "generated": "s"},
         '"graded" integer generated always as ((a_plus + a)) stored'),
        # Nullable, no default.
        ({"name": "instructor", "coltype": "text", "notnull": False,
          "coldefault": None, "identity": "", "generated": ""},
         '"instructor" text'),
    ]
    for column, expected in cases:
        got = clone.column_ddl(column)
        assert got == expected, f"{column['name']}: got {got!r}, want {expected!r}"


def test_generated_columns_are_not_inserted():
    """
    A stored generated column is computed by the target. Including it in the
    insert list is an error, and `grades` has two of them.
    """
    columns = [
        {"name": "term", "coltype": "integer", "notnull": True,
         "coldefault": None, "identity": "", "generated": ""},
        {"name": "graded", "coltype": "integer", "notnull": False,
         "coldefault": "(a + b)", "identity": "", "generated": "s"},
        {"name": "gpa", "coltype": "numeric", "notnull": False,
         "coldefault": "umd_gpa(a)", "identity": "", "generated": "s"},
    ]
    def respond(sql: str):
        if "contype = 'p'" in sql:
            return [{"name": "term"}]        # primary key lookup
        if "count(*)" in sql:
            return [{"count": 0}]            # empty table, so no batches run
        return []

    source = RecordingProject(responder=respond)
    target = RecordingProject()
    clone.copy_table(source, target, "grades", columns, batch=100, verbose=False)

    combined = " ".join(source.statements + target.statements)
    assert '"graded"' not in combined, "generated column reached the copy"
    assert '"gpa"' not in combined, "generated column reached the copy"


def test_dollar_quote_avoids_collision():
    assert clone.dollar_quote("plain") == "$jp$plain$jp$"
    # Content containing the tag must force a different one, or the statement
    # terminates early and the rest of the payload is parsed as SQL.
    collides = clone.dollar_quote("has $jp$ inside")
    assert collides.startswith("$jpx$"), collides
    assert collides.endswith("$jpx$"), collides


def test_generated_ddl_parses():
    """A representative CREATE TABLE, built the way the script builds them."""
    if not HAVE_PGLAST:
        return
    columns = [
        {"name": "id", "coltype": "bigint", "notnull": True,
         "coldefault": None, "identity": "d", "generated": ""},
        {"name": "name", "coltype": "text", "notnull": True,
         "coldefault": None, "identity": "", "generated": ""},
        {"name": "rating", "coltype": "numeric(3,2)", "notnull": False,
         "coldefault": None, "identity": "", "generated": ""},
        {"name": "graded", "coltype": "integer", "notnull": False,
         "coldefault": "(1 + 2)", "identity": "", "generated": "s"},
    ]
    body = ",\n    ".join(clone.column_ddl(c) for c in columns)
    failures = check_parses("create table", [f'create table "t" (\n    {body}\n);'])
    assert not failures, "\n".join(failures)


def test_policy_reconstruction_parses():
    """RLS policies are rebuilt from pg_policies rather than dumped."""
    # fetch_rls issues two queries with different result shapes.
    def respond(sql: str):
        if "relrowsecurity" in sql:
            return [{"name": "grades"}]
        return [{
            "schemaname": "public", "tablename": "grades",
            "policyname": "grades_public_read", "permissive": "PERMISSIVE",
            "roles": "{anon,authenticated}", "cmd": "SELECT",
            "qual": "true", "with_check": None,
        }]

    project = RecordingProject(responder=respond)
    enable, policies = clone.fetch_rls(project)
    assert enable == ['alter table "grades" enable row level security;'], enable
    assert len(policies) == 1
    statement = policies[0]
    assert "create policy" in statement
    assert "to anon, authenticated" in statement
    assert "using (true)" in statement
    failures = check_parses("policy", [statement])
    assert not failures, "\n".join(failures)


def test_policy_for_public_role_omits_to_clause():
    def respond(sql: str):
        if "relrowsecurity" in sql:
            return []
        return [{
            "schemaname": "public", "tablename": "grades", "policyname": "p",
            "permissive": "PERMISSIVE", "roles": "{public}", "cmd": "SELECT",
            "qual": "true", "with_check": None,
        }]

    project = RecordingProject(responder=respond)
    _, policies = clone.fetch_rls(project)
    assert " to " not in policies[0], policies[0]


def test_confirm_guard_is_required(monkeypatch=None):
    """
    The script drops the target's public schema, so it must refuse to run
    without the target ref typed out.
    """
    import subprocess
    env = {
        "SOURCE_REF": "sourceref", "SOURCE_PAT": "x",
        "TARGET_REF": "targetref", "TARGET_PAT": "y",
        "PATH": "/usr/bin:/bin",
    }
    result = subprocess.run(
        [sys.executable, str(ROOT / "db" / "clone_via_api.py")],
        capture_output=True, text=True, env=env,
    )
    assert result.returncode == 1, result.stdout + result.stderr
    assert "refusing to write" in result.stderr, result.stderr
    assert "--confirm targetref" in result.stderr, result.stderr


def test_same_project_is_refused():
    import subprocess
    env = {
        "SOURCE_REF": "sameref", "SOURCE_PAT": "x",
        "TARGET_REF": "sameref", "TARGET_PAT": "y",
        "PATH": "/usr/bin:/bin",
    }
    result = subprocess.run(
        [sys.executable, str(ROOT / "db" / "clone_via_api.py"), "--confirm", "sameref"],
        capture_output=True, text=True, env=env,
    )
    assert result.returncode == 1
    assert "same project" in result.stderr, result.stderr


if __name__ == "__main__":
    failures = 0
    statement_count = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            result = fn()
            if isinstance(result, int):
                statement_count = result
            print(f"  ok   {name}")
        except AssertionError as error:
            failures += 1
            print(f"  FAIL {name}: {error}")

    print()
    if not HAVE_PGLAST:
        print("NOTE: pglast not installed; SQL grammar checks were skipped.")
    else:
        print(f"{statement_count} generated statements parsed against PostgreSQL's grammar.")
    print(f"{failures} failure(s)." if failures else "All clone_via_api tests pass.")
    sys.exit(1 if failures else 0)
