#!/usr/bin/env python3
"""
Generate the SQL half of the name-normalization parity test.

The fixtures live in one place - `scraper/tests/fixtures/names.json` - and the
Python and TypeScript implementations read them directly. SQL cannot, so this
compiles them into a runnable script instead of anyone maintaining a second
copy by hand.

    python3 db/tests/generate_name_parity.py > db/tests/name_parity.sql
    psql "$DATABASE_DIRECT_URL" -f db/tests/name_parity.sql

The generated file is committed so it can be reviewed and run without this
script, but it is generated: edit the fixture, never the .sql.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FIXTURES = json.loads((ROOT / "tests" / "fixtures" / "names.json").read_text())


def sql_literal(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return "'" + str(value).replace("'", "''") + "'"


def emit_group(group: str, expression: str, title: str) -> list[str]:
    rows = [
        f"        ({sql_literal(case['input'])}, {sql_literal(case['expected'])})"
        for case in FIXTURES[group]
    ]
    return [
        f"-- {title}",
        "with cases (input, expected) as (values",
        ",\n".join(rows),
        "),",
        "results as (",
        f"    select input, expected, {expression} as actual from cases",
        ")",
        "select",
        f"    '{group}' as test,",
        "    input,",
        "    expected,",
        "    actual",
        "from results",
        "where actual is distinct from expected;",
        "",
    ]


def main() -> None:
    out: list[str] = [
        "-- GENERATED by db/tests/generate_name_parity.py - do not edit.",
        "-- Source of truth: scraper/tests/fixtures/names.json",
        "--",
        "-- Every query below returns ZERO ROWS when the SQL implementation agrees",
        "-- with the fixtures. Any row is a parity failure between the SQL functions",
        "-- and their Python and TypeScript twins, which means duplicate instructor",
        "-- records are being created somewhere.",
        "--",
        "--     psql \"$DATABASE_DIRECT_URL\" -f db/tests/name_parity.sql",
        "",
        "\\set ON_ERROR_STOP on",
        "",
    ]

    out += emit_group("normalize", "normalize_name(input)", "normalize_name()")
    out += emit_group("slugify", "slugify(input)", "slugify()")
    out += emit_group("denylisted", "is_instructor_denylisted(input)", "is_instructor_denylisted()")
    out += emit_group("first_last", "name_first_last(input)", "name_first_last()")
    out += emit_group("surname", "name_surname(input)", "name_surname()")

    out += [
        "-- The relationship slugify() is defined by. Zero rows expected.",
        "with cases (input) as (values",
        ",\n".join(
            f"        ({sql_literal(case['input'])})" for case in FIXTURES["normalize"]
        ),
        ")",
        "select 'slug_is_normalize_with_hyphens' as test, input",
        "from cases",
        "where slugify(input) is distinct from replace(normalize_name(input), ' ', '-');",
        "",
    ]

    print("\n".join(out))


if __name__ == "__main__":
    main()
