-- GENERATED by db/tests/generate_name_parity.py - do not edit.
-- Source of truth: scraper/tests/fixtures/names.json
--
-- Every query below returns ZERO ROWS when the SQL implementation agrees
-- with the fixtures. Any row is a parity failure between the SQL functions
-- and their Python and TypeScript twins, which means duplicate instructor
-- records are being created somewhere.
--
--     psql "$DATABASE_DIRECT_URL" -f db/tests/name_parity.sql

\set ON_ERROR_STOP on

-- normalize_name()
with cases (input, expected) as (values
        ('Shane Walsh', 'shane walsh'),
        ('Shane Bolles Walsh', 'shane bolles walsh'),
        ('Walsh, Shane Bolles', 'walsh shane bolles'),
        ('  Shane   Walsh  ', 'shane walsh'),
        ('SHANE WALSH', 'shane walsh'),
        ('Erin O''Brien', 'erin o brien'),
        ('Erin O’Brien', 'erin o brien'),
        ('Alice Smith-Jones', 'alice smith jones'),
        ('José García', 'jose garcia'),
        ('Zoë Müller', 'zoe muller'),
        ('Ana Peña', 'ana pena'),
        ('Åke Öberg', 'ake oberg'),
        ('John Smith Jr.', 'john smith jr'),
        ('John Smith III', 'john smith iii'),
        ('R. J. Smith', 'r j smith'),
        ('Smith, R.J.', 'smith r j'),
        ('Mary Jane Watson-Parker', 'mary jane watson parker'),
        ('de la Cruz, María', 'de la cruz maria'),
        ('Anne-Marie D''Angelo', 'anne marie d angelo'),
        ('  ', null),
        ('', null),
        ('...', null),
        ('TBA', 'tba'),
        ('Instructor: TBA', 'instructor tba')
),
results as (
    select input, expected, normalize_name(input) as actual from cases
)
select
    'normalize' as test,
    input,
    expected,
    actual
from results
where actual is distinct from expected;

-- slugify()
with cases (input, expected) as (values
        ('Shane Walsh', 'shane-walsh'),
        ('Shane Bolles Walsh', 'shane-bolles-walsh'),
        ('Erin O''Brien', 'erin-o-brien'),
        ('José García', 'jose-garcia'),
        ('Alice Smith-Jones', 'alice-smith-jones'),
        ('John Smith Jr.', 'john-smith-jr'),
        ('  Shane   Walsh  ', 'shane-walsh'),
        ('R. J. Smith', 'r-j-smith'),
        ('de la Cruz, María', 'de-la-cruz-maria'),
        ('', null),
        ('...', null)
),
results as (
    select input, expected, slugify(input) as actual from cases
)
select
    'slugify' as test,
    input,
    expected,
    actual
from results
where actual is distinct from expected;

-- is_instructor_denylisted()
with cases (input, expected) as (values
        ('TBA', true),
        ('tba', true),
        ('TBD', true),
        ('Staff', true),
        ('STAFF', true),
        ('Instructor: TBA', true),
        ('Instructor', true),
        ('', true),
        ('   ', true),
        ('Shane Walsh', false),
        ('Stafford Jones', false),
        ('Tabatha Bacon', false)
),
results as (
    select input, expected, is_instructor_denylisted(input) as actual from cases
)
select
    'denylisted' as test,
    input,
    expected,
    actual
from results
where actual is distinct from expected;

-- name_first_last()
with cases (input, expected) as (values
        ('shane bolles walsh', 'shane walsh'),
        ('shane walsh', 'shane walsh'),
        ('walsh', 'walsh'),
        ('mary jane watson parker', 'mary parker')
),
results as (
    select input, expected, name_first_last(input) as actual from cases
)
select
    'first_last' as test,
    input,
    expected,
    actual
from results
where actual is distinct from expected;

-- name_surname()
with cases (input, expected) as (values
        ('shane bolles walsh', 'walsh'),
        ('walsh', 'walsh'),
        ('de la cruz maria', 'maria')
),
results as (
    select input, expected, name_surname(input) as actual from cases
)
select
    'surname' as test,
    input,
    expected,
    actual
from results
where actual is distinct from expected;

-- The relationship slugify() is defined by. Zero rows expected.
with cases (input) as (values
        ('Shane Walsh'),
        ('Shane Bolles Walsh'),
        ('Walsh, Shane Bolles'),
        ('  Shane   Walsh  '),
        ('SHANE WALSH'),
        ('Erin O''Brien'),
        ('Erin O’Brien'),
        ('Alice Smith-Jones'),
        ('José García'),
        ('Zoë Müller'),
        ('Ana Peña'),
        ('Åke Öberg'),
        ('John Smith Jr.'),
        ('John Smith III'),
        ('R. J. Smith'),
        ('Smith, R.J.'),
        ('Mary Jane Watson-Parker'),
        ('de la Cruz, María'),
        ('Anne-Marie D''Angelo'),
        ('  '),
        (''),
        ('...'),
        ('TBA'),
        ('Instructor: TBA')
)
select 'slug_is_normalize_with_hyphens' as test, input
from cases
where slugify(input) is distinct from replace(normalize_name(input), ' ', '-');

