-- Production's schema before the grades/instructor migration: the tables, view,
-- materialized view and function created through the Supabase dashboard, with
-- their grants, RLS and default privileges.
--
-- Generated 2026-09-12 by `supabase db dump --linked` (schema only, blank runs
-- squeezed). It exists so `supabase/migrations/` builds the whole schema from
-- nothing. Production already has all of it, so mark it applied there rather
-- than running it:
--
--   npx supabase migration repair 20260912200000 --status applied --linked
--
-- Not captured, because a schema dump cannot see it: the pg_cron job that called
-- refresh_active_instructors() nightly. The next migration removes both.
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."refresh_active_instructors"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
begin
    refresh materialized view active_instructors;
end;
$$;

ALTER FUNCTION "public"."refresh_active_instructors"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."instructors" (
    "slug" "text" NOT NULL,
    "name" "text",
    "average_rating" real
);

ALTER TABLE "public"."instructors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sections" (
    "course_code" "text" NOT NULL,
    "sec_code" "text" NOT NULL,
    "instructors" "text"[] NOT NULL,
    "meetings" "text"[] NOT NULL,
    "open_seats" smallint NOT NULL,
    "total_seats" smallint NOT NULL,
    "waitlist" smallint NOT NULL,
    "holdfile" smallint
);

ALTER TABLE "public"."sections" OWNER TO "postgres";

CREATE MATERIALIZED VIEW "public"."active_instructors" AS
 SELECT DISTINCT "i"."slug",
    "i"."name",
    "i"."average_rating"
   FROM ("public"."instructors" "i"
     JOIN "public"."sections" "s" ON (("i"."name" = ANY ("s"."instructors"))))
  WITH NO DATA;

ALTER MATERIALIZED VIEW "public"."active_instructors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."courses" (
    "course_code" "text" NOT NULL,
    "name" "text" NOT NULL,
    "min_credits" smallint NOT NULL,
    "max_credits" smallint,
    "gen_eds" "text"[],
    "conditions" "text"[],
    "description" "text"
);

ALTER TABLE "public"."courses" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."departments" (
    "dept_code" "text" NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."departments" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."dept_codes" AS
 SELECT DISTINCT "left"("course_code", 4) AS "dept_code"
   FROM "public"."courses";

ALTER VIEW "public"."dept_codes" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_data" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."user_data" OWNER TO "postgres";

ALTER TABLE "public"."user_data" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "Courses_pkey" PRIMARY KEY ("course_code");

ALTER TABLE ONLY "public"."instructors"
    ADD CONSTRAINT "Instructors_pkey" PRIMARY KEY ("slug");

ALTER TABLE ONLY "public"."sections"
    ADD CONSTRAINT "Sections_pkey" PRIMARY KEY ("course_code", "sec_code");

ALTER TABLE ONLY "public"."departments"
    ADD CONSTRAINT "departments_pkey" PRIMARY KEY ("dept_code");

ALTER TABLE ONLY "public"."user_data"
    ADD CONSTRAINT "user_data_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sections"
    ADD CONSTRAINT "Sections_course_code_fkey" FOREIGN KEY ("course_code") REFERENCES "public"."courses"("course_code") ON DELETE CASCADE;

CREATE POLICY "Enable read access for all users" ON "public"."courses" FOR SELECT USING (true);

ALTER TABLE "public"."courses" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."departments" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."instructors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sections" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_data" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."refresh_active_instructors"() TO "anon";
GRANT ALL ON FUNCTION "public"."refresh_active_instructors"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."refresh_active_instructors"() TO "service_role";

GRANT ALL ON TABLE "public"."instructors" TO "anon";
GRANT ALL ON TABLE "public"."instructors" TO "authenticated";
GRANT ALL ON TABLE "public"."instructors" TO "service_role";

GRANT ALL ON TABLE "public"."sections" TO "anon";
GRANT ALL ON TABLE "public"."sections" TO "authenticated";
GRANT ALL ON TABLE "public"."sections" TO "service_role";

GRANT ALL ON TABLE "public"."active_instructors" TO "anon";
GRANT ALL ON TABLE "public"."active_instructors" TO "authenticated";
GRANT ALL ON TABLE "public"."active_instructors" TO "service_role";

GRANT ALL ON TABLE "public"."courses" TO "anon";
GRANT ALL ON TABLE "public"."courses" TO "authenticated";
GRANT ALL ON TABLE "public"."courses" TO "service_role";

GRANT ALL ON TABLE "public"."departments" TO "anon";
GRANT ALL ON TABLE "public"."departments" TO "authenticated";
GRANT ALL ON TABLE "public"."departments" TO "service_role";

GRANT ALL ON TABLE "public"."dept_codes" TO "anon";
GRANT ALL ON TABLE "public"."dept_codes" TO "authenticated";
GRANT ALL ON TABLE "public"."dept_codes" TO "service_role";

GRANT ALL ON TABLE "public"."user_data" TO "anon";
GRANT ALL ON TABLE "public"."user_data" TO "authenticated";
GRANT ALL ON TABLE "public"."user_data" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_data_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_data_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_data_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

